### ISSUE TITLE
[Proposal] Improvement for node inputs/properties

### ISSUE THREAD

**Issue by zauberparacelsus** [RodZill4/material-maker#113]
One feature from blender's nodes which may be useful to implement is allowing values to be directly entered into a node's input, which would reduce the amount of node clutter on the screen [EG: not having to enter Uniform/Grayscale nodes everywhere]

And building on that, the properties of some of the procedural texture nodes could be driven by other nodes.  For example, the brick node could have its mortar property driven by a noise node, randomizing the thickness.

**Comment by RodZill4** [comment]
I don't know Blender that much. How do you enter a value into a node's input?

It is possible (and quite easy) to add inputs to existing nodes to affect parameters, but not all parameters could be affected by inputs (for example, the Repeat, Rows and Columns parameters of Bricks), so that would be changed on each node.
I'll make the necessary change in nodes to be able to "skip" input slots so inputs can be placed in front of their corresponding parameter.

**Comment by zauberparacelsus** [comment]
With blender, a node's inputs each have a field to their right where you can enter a value or color, depending on the input type.  If a "noodle" is connected to the node input, then this field gets hidden.  I've taken a screenshot to demonstrate this:

![screenshot of blender](https://i.gyazo.com/1845e1901b0a0ac7a193bb712758687c.png)

**Comment by RodZill4** [comment]
Hmm this will actually make sense with very few inputs IMHO. But if I missed inputs that could be constant in many cases, please don't hesitate to tell me.

**Comment by RodZill4** [comment]
Was fixed for 0.92 (on relevant nodes).
