### ISSUE TITLE
[Proposal] Add non-random-offset and random-colors to the tiler node.

### ISSUE THREAD

**Issue by huttyblue** [RodZill4/material-maker#124]
![image](https://user-images.githubusercontent.com/38145037/82988498-e141a600-9fbe-11ea-8f67-213203b8500b.png)

There currently isn't a really good option for making customized hex-grids. The beehive node works but it doesn't have much flexibility. What would be helpful is if the tiler node got a new value to dictate how far each row gets offset. Setting it to 0.5 would offset the next row by half a tile making a hex-grid aligned pattern.  Additionally, the tiler node should have the extra outputs the bricks node has, giving it access to random colors and such.

**Comment by RodZill4** [comment]
Hmm the randomized tile color output for the Tiler is not really possible, because tiled patterns can overlap (so they would end up not being painted with the right color). Could you describe a few use cases for this.
BTW, next release will have a random Value (for BW tiler)/Opacity (for Color Tiler) parameter to add more variations. I guess it would be possible to combine this with a gradient to obtain tiles with different colors.

![image](https://user-images.githubusercontent.com/6957908/83053603-42b25500-a051-11ea-9d63-ec2f1dee4ebe.png)

The line offset is definitely a good idea (with an obvious usage for roof tiles). Not sure if the offset should apply to odd lines (lines would alternate between 2 alignments) or cumulate (some kind of shear deform of the grid)?

**Comment by RodZill4** [comment]
Hmm I was wrong, it's quite easy to output a random color per tile on greyscale Tiler (and it also applies to greyscale Splatter). When tiles overlap, the highest value of the greyscale channel will select the tile color.
Here's the result with the Splatter node (Brightness/Contrast nodes are only used to show both outputs), the Tiler node will give similar result (with tiles aligned on a grid):
![image](https://user-images.githubusercontent.com/6957908/83936548-f4295700-a7c4-11ea-9c2c-8b3d55bf60f1.png)
@huttyblue is this was you expect?

**Comment by huttyblue** [comment]
Yes this is what I was wanting for the tile colors/values. Looks like its working great.

**Comment by RodZill4** [comment]
Was fixed for 0.92
