### ISSUE TITLE
Show first node output in graph by default

### ISSUE THREAD

**Issue by escargot-sans-gluten** [RodZill4/material-maker#173]
**Feature/enhancement description:**
Right now when you add a node none of the outputs is show by default:
![node no output shown](https://user-images.githubusercontent.com/44414272/92992910-82ad2300-f4ee-11ea-8455-07d279a7d8e5.png)

In practice I found it anoying because I usually want to see each step of the process in the graph:
![graph nodes outputs preview](https://user-images.githubusercontent.com/44414272/92993003-ff400180-f4ee-11ea-87e1-b3ff4a5dda03.png)

I think it would improve UX if there was by default a preview of the first output when you add a node.
If it were to be added, this could maybe be a global option since it can also be seen as bloating for some users.

**Comment by RodZill4** [comment]
I don't this it is a nice default behavior, nodes are currently big enough. I'm considering providing an alternace view where node would hold a preview and parameters would be in a panel or a popup, but this would not be convenient when using remote nodes.

Plus showing all preview can be bad for performance.

It could still be an option in the preferences dialog, but not enabled by default.

**Comment by Jummit** [comment]
I would love a way to toggle previews of all nodes, just as a one time peek if you want to visualize what is going on.

**Comment by Takanu** [comment]
I think a one time toggle would be cool (though be warned if you have a big project you'll be waiting a while).

I dont think constant previews work so well for this node editor though mainly because it takes the same design approach as Blender where all parameters are exposed on the node itself rather than in something like Substance Designer where they're hidden in a sub-menu - complex node groups already get pretty tall and not all nodes need previews.

**Comment by Tar0x** [comment]
Yes, I can only confirm, that something like in Substance Designer would be cool. By that I mean nodes would show only previews and all parameters would be in separated properties pannel. This would be usefull especially for complex custom nodes with ten thousand parameters
