### ISSUE TITLE
Lock seed by default

### ISSUE THREAD

**Issue by escargot-sans-gluten** [RodZill4/material-maker#176]
**Feature/enhancement description:**

Currently, the seed for randomness-dependent nodes is unlocked by default and changed each time the node is moved.
I believe it should be locked by default because most often, one is ok with a plain random seed and no customisation.
Furthermore, an unlocked seed provides inconveniences if the user didn't bother turning it off on each node:
- Moving nodes that change every frame create very annoying results in both previews. This happen when you just drop and move e.g. any noise node.
- If the node is up in the graph, it takes a while to regenerate everything when reordering the graph.
- Since the button is so small, it is tedious to turn it off.

I think unlocking the seed should be reserved to cases where the user needs it.
Another option to solve these problems should be to add an explicit seed field to relevant nodes, randomly filled for each new node.

**Comment by RodZill4** [comment]
Hmm I will remove this "modify seed when moving node" feature, at least as a default behavior. Seeds will be rerolled by clicking on the dice icon (not decided which mouse button will be used since locking seed is still required). The current behavior is a problem if you need 2 nodes with the same seed, but unlocked randomness (which is a valid and not-so-uncommon use case).
This is more or less a duplicate of #79.

**Comment by escargot-sans-gluten** [comment]
OK, great!
I'm closing this now, then.

**Comment by unfa** [comment]
Couldn't seed be controlled manually with a number filed and a "randomize" button?
If a user wants a few noise nodes to have the same seed, he could just copy paste the seed number, right?
