### ISSUE TITLE
16 quality improvements proposal

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#202]
**1. when filling up parameter with decimal number, automatically convert decimal point "," to "."**
- users wouldn't have to switch from numeric keyboard to point button and back 

**2. Change the behaviour of LMB dragging over parameter number to select decimals instead of behaving as a slider.** 
- I know that it's possible to doubleclick to select whole number, but sometimes it behaves like slider, so basically I end up with changing a mll number between those clicks
- you may LMB drag on property name to behave as a slider
- See this for example https://youtu.be/Tsv8UGqDibc?t=767 .... but with LMB and without those multiple of ten :)

**3. field for typing custom seed value**
- dice is great, but sometimes you need "exact random values" for something or simply if you need to change it back to the previous version, it's impossible to get the same variation as before 

**4. opportunity to add own HDRIs and more default HDRIs**

**5. opportunity to rotate HDRI**
- while holding shift+LMB over 3D viewport

**6. opportunity to change generator node: tilling/no tilling (no repeat)**

**7. new basic shape node: crescent (navette = marquise shape)**
- it's really great staring point for foliage materials and now it's hard to make, only with several nodes

**8. opportunity to mute node (disable)**
- prevent selected node from cooking by disabling it (eye button or pressing M)

**9. alt+LMB drag a node on a connection line to plug it inbetween nodes**
- nodes with multiple inputs should choose the first input/output avaiable (probably)

**10. more blend modes for Tiler node**
- now it's only lighten mode avaiable I guess. 

**11. zooming out with scrollwheel instead with scrollwheel+ctrl**
- I guess there's more need to zoom in/out than scrolling down, even in this program, where the graph flows from left to right instead from top to bottom

**12. minimap**
- like in Nuke for exmple

**13. oportunity to make "nodes" on connecting lines, so people can reroute paths or use it as an input for multiple nodes**
- this https://i.imgur.com/e0JyLV4.png

**14. Undo/redo**

**15. in parameters node add arrows for changing order of parameters**

**16. more export options**
- such as ability to choose specific channel for storing information (useful for RGB stacking channels such as metalic, roughness and height into one texture)
- export textures from default material output node checkbox .... most of the time I use those export nodes, because of more customization and I find it a bit useless, because export from material output node clutters the folder with unnesessary diplicate textures i don't want to have so I have to delete them later

**Comment by Calinou** [comment]
Please open one issue per feature request, so that they can be discussed and tracked individually.

**Comment by RodZill4** [comment]
1. This can be done only with numbers, not expressions

2. there is no (not always at least) property name for float input controls. But it's certainly possible to disable the drag behavior when the text entry has the focus.

3. No. No entering a seed number. That's pure nonsense. Being able to undo a seed change, yes, definitely. Keeping a seed when copying a node (which happens already when the node is seed-locked), yes.

4. Yes. That's somewhere in the roadmap already. For the EXR problem, I think I will patch and compile Godot.

5. You can already rotate the camera and the object. Not sure it's useful.

6. Not sure I understand. Which generator node ?

7. You know you can create groups and add them to your user library, right? Sure we can add more shapes, but I want users to reuse (and share) whatever they create as much as possible. ;) But yes, the more, the merrier.

8. Only buffer nodes are cooked. So yes, we could make it possible to disable buffers (I added a button to completely pause rendering in latest dev build).

9. Yes, this requires Godot updates, not sure when they will be merged.

10. Do you have a list of useful blend modes in that context?

11. That behavior is in Godot, not sure if I can disable it.

12. Yes.

13. See (9).

14. This is #6. Best procrastination topic ever (because it's a PITA to implement).

15. You mean Remote node? Yes.

16. Hmm I have ideas for export, such as adding parameters. There could be a "Custom" export option that don't export anything from Material. You could add it yourself easily if you don't mind hacking the material.mmg file.
