### ISSUE TITLE
Export node in group node issue

### ISSUE THREAD

**Issue by Tar0x** [RodZill4/material-maker#216]
**Material Maker version:**
0.93

**OS/device including version:**
Win10

**Issue description:**
When using export node inside group node, it does not export anything when exporting material. I am not sure, if it is a bug or missing feature :)

**Comment by bonbonmiel** [comment]
I personnally don't see why it should behave like this. What would happen if you use the same group multiple times?
On top of that, it would also add hard to track "export sources".
Adding the texture you want as an output from the group and explicitely exporting it is better practice imho, but I am genuinely curious about use cases for this.

**Comment by RodZill4** [comment]
Yeah, @bonbonmiel is right, exports in groups are not enabled because this could generate files you don't want (for example if you use a group node you didn't create yourself).

But I understand potential use cases: create a group node that generates exports for an unsupported target. But the Material node can be updated easily, so if you need a new target, please just submit a .ptex with all export nodes you need so I can add it for next release (and/or provide a patch for current Material Maker release).

**Comment by Tar0x** [comment]
I wanted to make export setting special for my project, so I don't have to add like 10 nodes and fill up suffixes every time for each material :)

**Comment by RodZill4** [comment]
Maybe it's not obvious, but you can save several nodes (with interconnexions) in the user library (just select all of them, use tools->add selected node to user library). So you could just create a lib entry for all your export nodes.

**Comment by Tar0x** [comment]
Omg, why didn't you tell it before? <3 Thank you so much :)
