### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Jummit** [RodZill4/material-maker#242]
**Warning: I don't know how exactly Material Maker works internally, so any assumptions I make about texture generation may be wrong.**

**Feature/enhancement description:**

When working with complex node graphs, performance can quickly drop while tweaking parameters, especially with float values. These are some possible solutions I could come up with:

1. Only generate the preview after the user stopped editing the float.
  This would make it less laggy, but also less interactive.
2. Optimize the generation of textures by storing the result of each node as a texture,
  and using that instead of integrating the node into a shader.
  This is simillar to using a Buffer node, which greatly improved performance for me.
3. The 2D preview could be optimized, as my FPS is low when I have it open.
  Maybe it could only be updated when the result changed.
4. I noticed was that textures where recalculated even if no preview was opened.
  It would be nice to generate these previews on demand.
5. The generated shaders could be cached and only the shader_params could be changed when a value is tweaked. Shader generation probably causes one of the biggest performance hits.

I know this is could be a huge task and may require lots of restructuring of the codebase, but I am opening this issue to start a discussion about possible approaches.

**Comment by Calinou** [comment]
> Only generate the preview after the user stopped editing the float.

We can have a middle ground solution by implementing *debouncing*. In other words, only update the preview when the value hasn't changed for more than 0.3 seconds (for instance).

**Comment by RodZill4** [comment]
The main reason why previews are rendered as shaders is that they update very smoothly when float parameters are modified in "small" graphs. What you're suggesting is basically to get back to how Material Maker was before 0.9 (that relied on debouncing to make rendering times bearable).

The actual solution to this problem (and the related, more important issue that causes Material Maker to crash whenever a generated shader becomes too complex) is:
- to keep graphs as simple as possible (i.e. not introduce sub-pixel details by setting parameters too high)
- to use buffers where needed

I know it makes Material Maker more difficult to use (than other similar tools), and I'm thinking about ways to detect where buffers should be inserted (and insert them automatically) to optimize rendering times.

**Comment by Jummit** [comment]
So debouncing would be a temporary fix, not the final solution.
You mention only inserting buffers on select nodes, but what's the problem with storing the result of every node? I guess the implementation would be simpler?

**Comment by RodZill4** [comment]
Yes, adding buffers everywhere would be a lot simpler. But buffers on all nodes would:
- make Material Maker a lot slower, because all buffers would have to be regenerated whenever a source is modified. Today, when a source is modified, only buffers are regenerated
- make the generated images a lot worse, because you'll lose details whenever storing images instead of keeping them in math (shader) form
- make it impossible to support animations and lots of cool features that are planned already

So the good solution is to insert buffers, but as few as possible. Today, it's the user's responsibility to add them, but I hope I can automate this.

It's probably also possible to modify previews so they can switch to a mode where they are rendered into a texture when FPS becomes too low. I don't think it would be too difficult to implement.

**Comment by Jummit** [comment]
Here is a way I found that makes buffers a lot faster, assuming you are using `Viewport.get_texture().get_data()` Instead of getting the data of the `ViewportTexture`, you can keep one Viewport per node and use its texture to avoid the expensive `get_data()` call.

**Comment by RodZill4** [comment]
I'm not sure how many viewports we can have at once. Did you actually implement this?

**Comment by Jummit** [comment]
I implemented it, and it ran smooth with around 10 Viewports. I don't think more would be a problem, because the viewports are only updated when needed.

**Comment by Takanu** [comment]
Performance is a pretty big consideration for me as Material Maker just hates the kinds of things I do to it that I could get away with in Substance Designer and it's making it increasingly hard to justify using.  Even if you're not doing the weird things I'm doing with non-photorealistic plants and plant generation, the demos me and someone else tried to make replicating that Studio Ghibli SD example brought the application to it's knees and it needs to be able to handle files that complex and those kinds of creative ambitions to be a flexible and reliable tool.

Ive been dealing with the weird bugs and quirks it throws at me and I can deal with them given the program's infancy, but this fundamentally bad performance has to be a priority.

**Comment by RodZill4** [comment]
There are performance problems only if you don't insert buffers or insert too many of them, or set parameter values that generate useless details.

There is no easy solution for this problem. There are lots of workarounds (see above) that look like good ideas but will actually decrease performance in most cases.

One big issue that prevents me from fixing this issue instantly is that there is no way of setting a "timeout" on rendering. If I could tell Godot to just stop rendering after, say, 0.5 seconds, I could instantly detect the node where it happens, and insert a buffer to solve the problem. As it is now (not sure if it is due to Godot, or GLES or my lack of knowledge) you can turn a smooth graph into an MM crash in just 1 connection.

**Comment by Takanu** [comment]
That complete Ghibli node someone provided had buffers from what I remember and mine certainly did when I stopped working on it.  There was nothing unnecessary about the details as they were needed to express the ideas that make the texture what it is, they both just crushed Material Maker.  

I totally understand the technical difficulties involved in the process, but as soon as you do something beyond simple concepts the application simply struggles to keep up with you, particularly if you use any nodes that involve scattering or texture layering.

**Comment by RodZill4** [comment]
Sorry for not being clear about unnecessary details, I was mentioning (for example) sub-pixel details that might be introduced in noise nodes when you increase the number of octaves. I meant the kind of details that increase the computation costs but don't contribute to the result.

I'm pretty sure there's always a solution to performance problems that consists in inserting a just few buffers, but I must admit it's difficult to find out where they should be added. Whenever I find time to implement a solution (that can insert buffers and remove useless ones), this will be done automatically.

**Comment by Takanu** [comment]
If there is I haven't found it, at some point when a file gets complex it'll take minutes to fully load and any changes in the middle of the chain take a painful amount of time to fully manifest, and because the texture generation is so process consuming I can't do anything else until everything regenerates.  Even the fact that the UI seizes up when you have a particularly toasty node selected just adds to the frustration.  

I tried to separate a file into two chunks just to try and make the finishing touches in a texture I was working on less painful earlier on and even just trying to do that was difficult because of just how unresponsive the app was.

**Comment by RodZill4** [comment]
Don't worry. MM already progressed thanks to your Ghibli example and it will continue.

After 0.94, I'll focus on undo/redo and performance (which means it's likely there won't be many new features) until Godot 4 is available.

**Comment by Jummit** [comment]
Oh, I completely forgot about one major optimization I made while developing Jummit/material-painter:
Caching the generated shaders and only changing the shader_params when a value is tweaked. That sped it up by a pretty large amount.

**Comment by RodZill4** [comment]
@Jummit Interesting... Not sure how it applies to Material Maker, because shaders are already reused, but I'm pretty sure they're still re-generated too often.

**Comment by Takanu** [comment]
@RodZill4 I appreciate that and I thank you for the hard work, I just really needed to make clear the performance problems that currently exist.

I think even if you spend a while trying to squeeze extra performance in the system and don't make much progress then the focus really needs to be on how the application handles usability while under heavy load.  Node selection and editing should be responsive at all times so even if the node is complex or if the app is baking textures I can still get things done and the app still feels enjoyable to use.

**Comment by belzecue** [comment]
MM runs very slow on my Linux Intel NUC box, which runs Blender & Godot without issue.  Would be great to see some optimisations and some configuration options to switch off resource-intensive features.  I would love to use MM on this NUC, which is my main device, but it's painful when the FPS hovers around <10 for anything other than the most basic node setup.

**Comment by Calinou** [comment]
> MM runs very slow on my Linux Intel NUC box, which runs Blender & Godot without issue. Would be great to see some optimisations and some configuration options to switch off resource-intensive features. I would love to use MM on this NUC, which is my main device, but it's painful when the FPS hovers around <10 for anything other than the most basic node setup.

NUCs only have integrated graphics, which likely explains why Material Maker runs slowly. As pretty much everything runs on the GPU in Material Maker, its performance is largely reliant on having a fast GPU available.

**Comment by RodZill4** [comment]
> MM runs very slow on my Linux Intel NUC box, which runs Blender & Godot without issue. Would be great to see some optimisations and some configuration options to switch off resource-intensive features. I would love to use MM on this NUC, which is my main device, but it's painful when the FPS hovers around <10 for anything other than the most basic node setup.

As @Calinou stated, Material Maker is all about generating and running shaders, so you will constantly hit your NUC's limitations. There are still a few things you can do:
- make sure you insert buffers in your graph where shaders become too complex (buffers have a rendering time indication to help you find the correct locations). Beware, inserting too many buffers will hurt performance as well
- there's a context menu on the progress bar near the FPS meter. You will want to disable automated renderer allocation, set the number of renderers to 1 and maybe limit the maximum resolution (this will save time while working on a material, and you can disable this for exports).

I'll still work on improving performance, anyway, since I hope I can release MM for Android one day.

**Comment by belzecue** [comment]
Thanks @Calinou and @RodZill4.  After tweaking the Preferences > Resolution/Detail settings, I achieved better fps, and it now runs satisfactorily on my Intel integrated graphics.

**Comment by Jummit** [comment]
Closing as this issue is not specific enough.
