### ISSUE TITLE
[0.94a4] Circle splatter only showing in the center of Preview2D when zoomed out.

### ISSUE THREAD

**Issue by some9000** [RodZill4/material-maker#269]
![material_maker_cIyzBd7zLh](https://user-images.githubusercontent.com/17021558/106354150-3bd29500-62f8-11eb-86ba-ef2b159dde62.png)

Is this intended behavior or a bug? Feels like the repats should be just clones of the center image...

**Edit:** Actually, seemingly, I need new glasses: No shapes of any sort show up there - the + and x rays made from shapes do not show either. So only gradients repeat.

**Comment by RodZill4** [comment]
No, it's the intended behavior. Material Maker does not manipulate images but shaders. Those shaders are defined beyond the generated image (and beyond pixel precision both in terms of size and value precision), that's what 2D preview shows.
If you want to see how your texture tiles, you just have to add a Transform node and set it in repeat mode.

Gradients repeat because that's how they are defined (not sure it's a good choice).

**Comment by some9000** [comment]
Ah, understood. I sort of suspected that, but didn't really find an explanation so far. Closing then.
