### ISSUE TITLE
Option to disable texture filtering in 3D Preview

### ISSUE THREAD

**Issue by petterthowsen** [RodZill4/material-maker#429]
**Feature/enhancement description:**
Pretty sure I'm not the only one who wants to procedurally generate pixel art textures. For that we need to disable texture filtering in the 3D preview.

Thanks!

**Comment by Calinou** [comment]
This used to be the case since https://github.com/RodZill4/material-maker/pull/40 was merged, but this code is no longer present as of https://github.com/RodZill4/material-maker/commit/c380e305d0b03d0113451e17ca533d2de85d7816.

**Comment by Keerp96** [comment]
This change has been reverted for some reason. Please consider re-enabling, as well as adding the option to disable filtering for any texture size via the Preview3D GUI

[Link to relevant blame](https://github.com/RodZill4/material-maker/blame/b57f878bcc6dadb9784375e076a60efdbdcf0686/addons/material_maker/engine/nodes/gen_material.gd#L163)

A workaround for others dealing with this issue, uncommenting the lines in gen_material.gd doesn't work because of the changes in Godot 4 - edit the /nodes/material.mmg file instead, the preview shader starts at line 3281.
You can add filter_nearest to all the sampler2D, like this:

```
"uniform sampler2D texture_albedo : source_color, filter_nearest; // $output(0)",
"uniform sampler2D texture_emission : hint_default_black, filter_nearest; // $output(2)",
"uniform sampler2D texture_normal : hint_normal, filter_nearest; // $output(3)",
"uniform sampler2D texture_orm : hint_default_white, filter_nearest; // $output(1)",
"uniform sampler2D texture_subsurface_scattering : hint_default_white, filter_nearest; // $output(5)",
"uniform sampler2D texture_depth : hint_default_black, filter_nearest; // $output(4)",
```
And also remove these lines:

```
"\tint texture_size = textureSize(texture_albedo, 0).x;",
"\tif (texture_size < 256) {",
"\t\tbase_uv = floor(float(texture_size)*base_uv+0.5)/float(texture_size);",
```

**Comment by shlongee** [comment]
> And also remove these lines:
> 
> ```
> "\tint texture_size = textureSize(texture_albedo, 0).x;",
> "\tif (texture_size < 256) {",
> "\t\tbase_uv = floor(float(texture_size)*base_uv+0.5)/float(texture_size);",
> ```
Preview stopped to work for me after removing these lines.

Simply adding filter_nearest worked just fine.
Thank you!
