### ISSUE TITLE
use redot instead of godot

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [RodZill4/material-maker#709]
Godot has failed. Nobody likes it right now
**Feature/enhancement description:**

Use a [clear engine version  Redot](https://github.com/Redot-Engine/redot-engine/)

**Comment by RodZill4** [comment]
Should I also remove the rainbow node ?

![image](https://github.com/user-attachments/assets/405535b5-a200-4d19-b331-c11c20fbb28f)

**Comment by boxyld** [comment]
too early to judge what will happen

at least we should wait to Friday and see

**Comment by TwilCynder** [comment]
I am confused, what purpose does Redot serve ? From what I understand it was created by people unhappy that the Godot Foundation was becoming "woke" or whatever, but as of now it just Godot with a different logo, and it doesn't seem like there is any plan to actually add features. You do realize that just making a fork does not do anything, and using Redot is litterally the same as using Godot on all accounts, including links (or lack thereof) with the Godot Foundation, right ?

**Comment by JD-The-65th** [comment]
As some people have commented, Godot is supported by people all over the world. Its success is a direct result of that, and it's only as good as it is now thanks to that. If Redot were to have any chance of being successful while standing on it's own, they would _literally have to become Godot, resources and all._ 

Redot as it stands right now, and for the forseeable future has very little structure in plan, it's community is actively fostering bad actors who tear the project apart from the inside, is lead by hypocrites, and will ultimately end up being a less stable version of Godot as it'll be unlikely to achieve the same level of Quality Control of Godot as their changes start to clash with Upstream. Ironic for this to be labeled as an "enhancement," because it'd be anything but.

![Screenshot_20241002_012855_X](https://github.com/user-attachments/assets/d8d9ad42-26b8-466a-bc1f-277df0a8e8a0)
![Screenshot_20240930_172346_Firefox](https://github.com/user-attachments/assets/b49e617f-5703-4a88-8e49-0e19aa56fcde)
![20240930_133813](https://github.com/user-attachments/assets/c2fb2122-cd16-45a1-b28b-84e136aac393)
![20241001_171828](https://github.com/user-attachments/assets/a5fe80eb-128e-4fa1-9d1f-27400abba63c)

**Comment by ivxvm** [comment]
There are some people unhappy with Godot becoming "woke" then there are some people unhappy with Godot having crazy unprofessional management banning everyone driven only by mood, skipping any rules to justify those bans. It takes some time to see which forks are going to push some rightwing agenda and which ones are just trying to focus on engineering values and stay away from politics and drama.

**Comment by boxyld** [comment]
yeah it's cool thing but the team is sadly still small but really active

it's nearly impossible to overcome godot but it can servive

we just should wait and see

**Comment by boxyld** [comment]
![Screenshot_20241004_030603_X.jpg](https://github.com/user-attachments/assets/c5a80014-707f-4acc-8631-2877ec4043ec)

Bro is hated even on Redot community💀

I don't blame them
